In [1]:
# https://cs229.stanford.edu/summer2020/cs229-linalg.pdf

<h3>Quick Recap on Vector Norms</h3>

Vector norms measure the "size" or "length" of a vector in different ways.

$\ell_{1}$ norm (Manhattan distance)
Sum of absolute values of vector elements

$||\mathbf{v}||_1 = \sum_{i=1}^n |v_i|$


$ $


$\ell_{2}$ norm (Euclidean norm)
Square root of the sum of squared elements

$||\mathbf{v}||_2 = \sqrt{\sum_{i=1}^n v_i^2}$


$ $


$\ell_{\infty}$ norm (Max norm)
Maximum absolute value of vector elements

$||\mathbf{v}||_\infty = \max(|v_1|, |v_2|, \dots, |v_n|)$


In [2]:
import numpy as np

# Vector
v = np.array([3, -4, 2])

# L1 Norm
l1_norm = np.linalg.norm(v, ord=1)
print(f"L1 Norm: {l1_norm}")

# L2 Norm
l2_norm = np.linalg.norm(v, ord=2)
print(f"L2 Norm: {l2_norm}")

# Infinity Norm
inf_norm = np.linalg.norm(v, ord=np.inf)
print(f"Infinity Norm: {inf_norm}")

L1 Norm: 9.0
L2 Norm: 5.385164807134504
Infinity Norm: 4.0


<h3>Basic Linear Algebra Concepts</h3>
<b>a. Vectors</b>

A vector is a one-dimensional array of numbers. It can represent points, directions, or quantities.

<b>b. Matrices</b>

A matrix is a two-dimensional array of numbers, often used to represent linear transformations or systems of equations.

In [3]:
# Example vector and matrix
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Vector:")
print(vector)

print("\nMatrix:")
print(matrix)

Vector:
[1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<b>c. Dot Product</b>

The dot product of two vectors is a scalar value. It measures their alignment

$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i$

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
print(f"Dot Product: {dot_product}")

Dot Product: 32


<b>d. Matrix Multiplication</b>

Matrix multiplication combines two matrices or a matrix and a vector.

$\mathbf{C} = \mathbf{A} \cdot \mathbf{B}$

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(A, B)
print("Matrix Product:")
print(matrix_product)

Matrix Product:
[[19 22]
 [43 50]]


<h4>Solving Systems of Linear Equations</h4>

$\mathbf{A} \mathbf{x} = \mathbf{b}$

You can solve for $\mathbf{x}$ using:

$\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$

In [6]:
A = np.array([[2, 1], [1, -1]])
b = np.array([3, 1])

x = np.linalg.solve(A, b)
print(f"Solution for x: {x}")

Solution for x: [1.33333333 0.33333333]


<h4>Eigenvalues and Eigenvectors</h4>

$\mathbf{A} \mathbf{v} = \lambda \mathbf{v}$

where

$\mathbf{v}$ is an Eigenvector

$\lambda$ is an Eigenvalue




In [7]:
A = np.array([[4, -2], [1, 1]])

eigenvalues, eigenvector = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvector}")

Eigenvalues: [3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


<h3>Matrix Math</h3>

$\text{1. Matrix Addition and Subtraction}$

$\mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$

$\mathbf{B} = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$

$\text{Addition: } \mathbf{C} = \mathbf{A} + \mathbf{B} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}$

$\text{Subtraction: } \mathbf{D} = \mathbf{A} - \mathbf{B} = \begin{bmatrix} -4 & -4 \\ -4 & -4 \end{bmatrix}$

In [8]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C = A + B

# Matrix subtraction
D = A - B

print("Matrix Addition:\n", C)
print("Matrix Subtraction:\n", D)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


$ $


$\text{2. Matrix Multiplication}$

$\text{Element-wise: } (\mathbf{A} \circ \mathbf{B}) = \begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix}$

$\text{Matrix Product: } \mathbf{A} \cdot \mathbf{B} = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}$

In [9]:
# Element-wise multiplication
elementwise_product = A * B

# Matrix multiplication
matrix_product = np.dot(A, B)  # Alternatively: A @ B

print("Element-wise Multiplication:\n", elementwise_product)
print("Matrix Multiplication:\n", matrix_product)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [10]:
A @ B

array([[19, 22],
       [43, 50]])

$ $


$\text{3. Transpose of a Matrix}$

$\mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$


$\mathbf{A}^T = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}$


In [11]:
transpose_A = A.T

print("Transpose of Matrix A:\n", transpose_A)

Transpose of Matrix A:
 [[1 3]
 [2 4]]


$\text{4. Determinant of a Matrix}$

$\text{Determinant: } \det(\mathbf{A}) = \begin{vmatrix} 1 & 2 \\ 3 & 4 \end{vmatrix} = -2$

In [12]:
det_A = np.linalg.det(A)

print("Determinant of Matrix A:", det_A)

Determinant of Matrix A: -2.0000000000000004


$\text{5. Inverse of a Matrix}$

$\mathbf{A}^{-1} = \frac{1}{\det(\mathbf{A})} \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}$

In [13]:
# Ensure the matrix is square and non-singular
inverse_A = np.linalg.inv(A)

print("Inverse of Matrix A:\n", inverse_A)

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


<h3>Real World Example: Movie Recommendations</h3>

Input Data

$\textbf{User Preferences Matrix} (U)$

Each row represents a user, and each column represents a genre. The values indicate how much a user likes a genre (on a scale from 0 to 1).

$U = \begin{bmatrix}
0.8 & 0.2 & 0.5 \\ 
0.3 & 0.9 & 0.1 \\ 
0.6 & 0.3 & 0.7
\end{bmatrix}$

$\textbf{Movie Features Matrix} (M)$

Each row represents a movie, and each column represents the movie's composition of genres. The values indicate the proportion of each genre in the movie.

$M = \begin{bmatrix}
0.9 & 0.1 & 0.4 \\ 
0.2 & 0.8 & 0.6 \\ 
0.5 & 0.5 & 0.7
\end{bmatrix}$

Calculation
To recommend movies, calculate the dot product to get a suitability score matrix:

$S = U \cdot M^T$

Where $M^T$ is the transpose of $M$:

$M^T = \begin{bmatrix}
0.9 & 0.2 & 0.5 \\ 
0.1 & 0.8 & 0.5 \\ 
0.4 & 0.6 & 0.7
\end{bmatrix}$

<h3>Python Implementation</h3>

In [14]:
import numpy as np

# User preferences matrix
U = np.array([
    [0.8, 0.2, 0.5],
    [0.3, 0.9, 0.1],
    [0.6, 0.3, 0.7]
])

# Movie features matrix
M = np.array([
    [0.9, 0.1, 0.4],
    [0.2, 0.8, 0.6],
    [0.5, 0.5, 0.7]
])

# Calculate the suitability score matrix
S = np.dot(U, M.T)

print("Suitability Scores:\n", S)


Suitability Scores:
 [[0.94 0.62 0.85]
 [0.4  0.84 0.67]
 [0.85 0.78 0.94]]


Each entry $S[i, j]$ in the matrix represents the suitability score of movie $j$ for user $i$. Higher scores indicate better recommendations. For example:


$S[0, 0] = 0.94$: Movie 1 is highly recommended for User 1.

$S[1, 2] = 0.67$: Movie 3 is moderately recommended for User 2.

$S[2, 2] = 0.94$: Movie 3 is highly recommended for User 3.

In [15]:
# Misc numpy stuff below this line

import numpy as np

np.c_[np.array([1,2,3]), np.array([4,5,6])]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
np.c_[np.array([1, 2, 3])]

array([[1],
       [2],
       [3]])

In [17]:
X = np.array([[1, 2], [3, 4], [5, 6]])
X.shape

(3, 2)

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
# add bias term, then column stack the arrays
X_w_bias = np.c_[np.ones(X.shape[0]), X]

In [20]:
X_w_bias

array([[1., 1., 2.],
       [1., 3., 4.],
       [1., 5., 6.]])