In [1]:
# https://cs229.stanford.edu/summer2020/cs229-linalg.pdf

<h3>Quick Recap on Vector Norms</h3>

L1 norm (Manhattan distance)

$L_{1}$

L2 norm (Euclidean norm)

$L_{2}$

In [12]:
# Misc numpy stuff below this line

import numpy as np

np.c_[np.array([1,2,3]), np.array([4,5,6])]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
np.c_[np.array([1, 2, 3])]

array([[1],
       [2],
       [3]])

In [14]:
X = np.array([[1, 2], [3, 4], [5, 6]])
X.shape

(3, 2)

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
# add bias term, then column stack the arrays
X_w_bias = np.c_[np.ones(X.shape[0]), X]

In [17]:
X_w_bias

array([[1., 1., 2.],
       [1., 3., 4.],
       [1., 5., 6.]])